# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/system";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A4FC-F6BC";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/nix";
      fsType = "zfs";
    };

  fileSystems."/home/maxwell/minecraft" =
    { device = "rpool/minecraft";
      fsType = "zfs";
    };

  fileSystems."/home/maxwell/minecraft/dynmap" =
    { device = "rpool/minecraft/dynmap";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0e0f3a1b-0406-40d5-a307-52e24ffe068e"; }
      { device = "/dev/disk/by-uuid/38ff6d66-d7f0-49ec-bfb8-63a296fd9ce9"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
