# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "ssdpool/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "ssdpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-id/nvme-eui.e8238fa6bf530001001b444a4435f0f0-part1";
      fsType = "vfat";
    };

  fileSystems."/ssdpool" =
    { device = "ssdpool";
      fsType = "zfs";
    };

  fileSystems."/rustpool" =
    { device = "rustpool";
      fsType = "zfs";
    };

  fileSystems."/mnt/media" =
    { device = "rustpool/media";
      fsType = "zfs";
    };

  fileSystems."/srv/containers" =
    { device = "ssdpool/containers";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nix.settings.max-jobs = lib.mkDefault 16;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
