#ENC[AES256_GCM,data:Pp+NusGUbIkycrpwjJOQgdiOUPUYmicrcR3pHtjs,iv:E+Vin3F5WyaWQsYrGekS47Bt/rbGIcuB+0x+opm091s=,tag:5neZfmSl4/cErZA1ASfaew==,type:comment]
photoprism_admin: ENC[AES256_GCM,data:jnBYD5vJvV/FhGIYcg+eKNvfouQq9N4hMCOA27doiwIn0msH2cnWX3aguBeHvmCqtwNopZE+piZbLFrS,iv:oNCpvSrCDSM30Fg+OYqrXDcu+a4PwZfiHQjSVdPROSc=,tag:z5zVsY4fYUCwi1Iajpw2SA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y832x8gp8lt7tzl7m03cfvmuaqlf58fdgvyc3gprpkdv9cve5yxqk4mkw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYkJWUGZHVDRZeHB2d2J2
            bks2Y1hPUTRsK1FXU1hCNllBMUZTRnh1T1Z3CmJiSk5JeW1DejR1THlvczZkaC9i
            TzRrVXl6OUxJNEtDaS9UR0pkUk1IeGsKLS0tIHJUeCsrMjlydGdraTVPVDJSbURG
            dW1mK3Jsd2JKTDd6SnBPd2MrQno3ZXMKThh/ciwCJyJUwhI+Qoi6uyaVI+u3herK
            +UqmJzX3kqSxNG82RMmJfqPmHkbAJlBJ4J1lKZ4PGN7GHlGVWhonjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12mql9lrqmp6yvrr9gh0kuuwnxn2hkvcku7x620vgtj6r568zfq7skkpajf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVHMxaDhGTXZBdGpZMjhC
            TnJGMUd4cUZhZVlxMHZpbVdJTnBtdkh1RmlVCkgwSWVReUFpcTFnbDB1bnI3dGht
            YzFid29hdDFpcUc3NzRCUHFCOEIyOTQKLS0tIHFENmtRak0yR1plYmZKUnpIeUJn
            VjRIc2FHWTNjQ0RkUU5zallubmpBSTAKiJ1JHlONoGqEUipLSp119H3dGuuvvu0G
            t1uXZrWHvI1rOTYGsv+ID+kZMXzkVLDkrECGy7hfZtUYCRhEtz8DhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13d0wge5xgtd8yvfak9lrhy5ee0yus7uecwhh0cpyqs59yv2ypveqt6evuh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R3hTS08zblVSMjcxYXYw
            T2x5TEhVa1VGUUIxUktXNER3OXJVZGNUUGtJCjRrUzM0QU5pbWZOVXJjc05YUjYw
            WXpsVWhnVDdZTlJRUUdvNEZNakZWd0EKLS0tIE9FNGR3RGc0NnRLUk41T081enpr
            Wk1Ga0xoaGRMc1Z4RmNGeFJOQTFDL0UKu+yUova+YSGo+4FrGBtaoRFwSh+wqjki
            4N3JBHtl+jdanyANAnvezzkjNn6UCy5YL2abOrvRySamhlsM8yaaNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T20:24:52Z"
    mac: ENC[AES256_GCM,data:9qx2mCjsQFaDxWvcTT2l5pkn20G9kGoaie/5y+pC0y180pY0SMEgdf4IyGrIRMiLASWqeoQc7mCEBcNJek2GLtzbMsFCqCRKR6EKDNOdh7ayvNOlb9keO1/1K4Au0MP3jSTobksDkKYQuoGMFlPUVxernVmHjb/OoN2rmIrQNRA=,iv:RXw1Mow0ZQ0EmKx76ATec6DUY+PPkxWmqr2sKjRh1l0=,tag:AmPka7knZ9mqRb2vrXpfLQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
