nextcloud_admin: ENC[AES256_GCM,data:95pEwAJk/pMC/9FGl+fYVAx33YHG6AI27jvMTc54GzXS7zT7Vy87dOpeO+1mQ6v474DXFzlZysGfmqFB,iv:R+qhpnT3B500cFMqVmRYqYmsjqQ4+SMO8zvOyuNB4KQ=,tag:vE8CzTJ8wxlaVUX26xAYlA==,type:str]
photoprism_admin: ENC[AES256_GCM,data:SZMCDxvm2c4zQ69mru7ObJ+Zf3OkkYsR5mrZqTmPuO440mzNSWDij7Xth+OdVJrAkH86iZWrk+S7MGkl,iv:4Fgwx6zHR3YL+382WgD3ZoXyqn7xpYnZjuySxm7jtGI=,tag:P9Fs57Gh5vwgaDVDyW+1dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y832x8gp8lt7tzl7m03cfvmuaqlf58fdgvyc3gprpkdv9cve5yxqk4mkw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYkJWUGZHVDRZeHB2d2J2
            bks2Y1hPUTRsK1FXU1hCNllBMUZTRnh1T1Z3CmJiSk5JeW1DejR1THlvczZkaC9i
            TzRrVXl6OUxJNEtDaS9UR0pkUk1IeGsKLS0tIHJUeCsrMjlydGdraTVPVDJSbURG
            dW1mK3Jsd2JKTDd6SnBPd2MrQno3ZXMKThh/ciwCJyJUwhI+Qoi6uyaVI+u3herK
            +UqmJzX3kqSxNG82RMmJfqPmHkbAJlBJ4J1lKZ4PGN7GHlGVWhonjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12mql9lrqmp6yvrr9gh0kuuwnxn2hkvcku7x620vgtj6r568zfq7skkpajf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVHMxaDhGTXZBdGpZMjhC
            TnJGMUd4cUZhZVlxMHZpbVdJTnBtdkh1RmlVCkgwSWVReUFpcTFnbDB1bnI3dGht
            YzFid29hdDFpcUc3NzRCUHFCOEIyOTQKLS0tIHFENmtRak0yR1plYmZKUnpIeUJn
            VjRIc2FHWTNjQ0RkUU5zallubmpBSTAKiJ1JHlONoGqEUipLSp119H3dGuuvvu0G
            t1uXZrWHvI1rOTYGsv+ID+kZMXzkVLDkrECGy7hfZtUYCRhEtz8DhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13d0wge5xgtd8yvfak9lrhy5ee0yus7uecwhh0cpyqs59yv2ypveqt6evuh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R3hTS08zblVSMjcxYXYw
            T2x5TEhVa1VGUUIxUktXNER3OXJVZGNUUGtJCjRrUzM0QU5pbWZOVXJjc05YUjYw
            WXpsVWhnVDdZTlJRUUdvNEZNakZWd0EKLS0tIE9FNGR3RGc0NnRLUk41T081enpr
            Wk1Ga0xoaGRMc1Z4RmNGeFJOQTFDL0UKu+yUova+YSGo+4FrGBtaoRFwSh+wqjki
            4N3JBHtl+jdanyANAnvezzkjNn6UCy5YL2abOrvRySamhlsM8yaaNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T04:46:52Z"
    mac: ENC[AES256_GCM,data:8i4KDLQGRWJi/XhFZsJ2rRpNbJqtHXgwRa2vFTt+V/rYE7cYrqd6qDtB+0k3YUB+xoLqJ/Y1vE69nuGOq9gg3L8vGjd3lzgmScF/KIIiT0guuMw+7Qe0xwhoH4ylKAGMd+8EVMyWu82co2YHgiiiu/yYVtFpTL3F+tELuRdwupg=,iv:+DfF6psZtMoGpUYcPIJ7FBbmkbckEMWatp3cH83mUrI=,tag:j9bYA9DQpT/Eeu3nfTeoNQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
