nextcloud_admin: ENC[AES256_GCM,data:95pEwAJk/pMC/9FGl+fYVAx33YHG6AI27jvMTc54GzXS7zT7Vy87dOpeO+1mQ6v474DXFzlZysGfmqFB,iv:R+qhpnT3B500cFMqVmRYqYmsjqQ4+SMO8zvOyuNB4KQ=,tag:vE8CzTJ8wxlaVUX26xAYlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y832x8gp8lt7tzl7m03cfvmuaqlf58fdgvyc3gprpkdv9cve5yxqk4mkw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYkJWUGZHVDRZeHB2d2J2
            bks2Y1hPUTRsK1FXU1hCNllBMUZTRnh1T1Z3CmJiSk5JeW1DejR1THlvczZkaC9i
            TzRrVXl6OUxJNEtDaS9UR0pkUk1IeGsKLS0tIHJUeCsrMjlydGdraTVPVDJSbURG
            dW1mK3Jsd2JKTDd6SnBPd2MrQno3ZXMKThh/ciwCJyJUwhI+Qoi6uyaVI+u3herK
            +UqmJzX3kqSxNG82RMmJfqPmHkbAJlBJ4J1lKZ4PGN7GHlGVWhonjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12mql9lrqmp6yvrr9gh0kuuwnxn2hkvcku7x620vgtj6r568zfq7skkpajf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVHMxaDhGTXZBdGpZMjhC
            TnJGMUd4cUZhZVlxMHZpbVdJTnBtdkh1RmlVCkgwSWVReUFpcTFnbDB1bnI3dGht
            YzFid29hdDFpcUc3NzRCUHFCOEIyOTQKLS0tIHFENmtRak0yR1plYmZKUnpIeUJn
            VjRIc2FHWTNjQ0RkUU5zallubmpBSTAKiJ1JHlONoGqEUipLSp119H3dGuuvvu0G
            t1uXZrWHvI1rOTYGsv+ID+kZMXzkVLDkrECGy7hfZtUYCRhEtz8DhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13d0wge5xgtd8yvfak9lrhy5ee0yus7uecwhh0cpyqs59yv2ypveqt6evuh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R3hTS08zblVSMjcxYXYw
            T2x5TEhVa1VGUUIxUktXNER3OXJVZGNUUGtJCjRrUzM0QU5pbWZOVXJjc05YUjYw
            WXpsVWhnVDdZTlJRUUdvNEZNakZWd0EKLS0tIE9FNGR3RGc0NnRLUk41T081enpr
            Wk1Ga0xoaGRMc1Z4RmNGeFJOQTFDL0UKu+yUova+YSGo+4FrGBtaoRFwSh+wqjki
            4N3JBHtl+jdanyANAnvezzkjNn6UCy5YL2abOrvRySamhlsM8yaaNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T04:28:29Z"
    mac: ENC[AES256_GCM,data:dJUEGUqic0zkQVujKDj6jLGc8Fxpum/MrAywMxgNYsQt+j8CJ/3RE5JJ7g4qe8DKl6CVMJ0x3NfpG+k05AAWfSzGEpHL1lwbAC01jxEEPERK3FJXWD332rj1VioM9/kAmeWT8eiLys//zlft05MTlM5WVVQ+WyRUq22dH2gQrRo=,iv:UTGw4tCV68JemS7wWtM4Ru9yJ+njnQmaawrmCszt2C0=,tag:PtrjYgVF4InLTqW3dZAeig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
