nextcloud_admin: ENC[AES256_GCM,data:95pEwAJk/pMC/9FGl+fYVAx33YHG6AI27jvMTc54GzXS7zT7Vy87dOpeO+1mQ6v474DXFzlZysGfmqFB,iv:R+qhpnT3B500cFMqVmRYqYmsjqQ4+SMO8zvOyuNB4KQ=,tag:vE8CzTJ8wxlaVUX26xAYlA==,type:str]
photoprism_admin: ENC[AES256_GCM,data:SZMCDxvm2c4zQ69mru7ObJ+Zf3OkkYsR5mrZqTmPuO440mzNSWDij7Xth+OdVJrAkH86iZWrk+S7MGkl,iv:4Fgwx6zHR3YL+382WgD3ZoXyqn7xpYnZjuySxm7jtGI=,tag:P9Fs57Gh5vwgaDVDyW+1dg==,type:str]
lldap_jwt_secret: ENC[AES256_GCM,data:mf9NcjBDpKpj99Q1ZKhUvkuOr+9CTNSBihWnZNdC9BtaLP5La7USprbN0IuGYbPuRrLbSBCAj9Z4G5AlFf8g5w==,iv:JPYOa/ph+Dl3QQ/zrqzVEMEJmGz5X1fuDopFZrCT4pU=,tag:konnYvC4ifIlsU6+hRT6fg==,type:str]
lldap_user_pass: ENC[AES256_GCM,data:OIXS2bEQ0Pw4Ww9OKpGK+GhZ+oM=,iv:Yheq3CJlPqSzk25wvinjj4Z1QdH5oj4cdxqcc6xllNc=,tag:W3fFqknH0Ma5GxTs71OZEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y832x8gp8lt7tzl7m03cfvmuaqlf58fdgvyc3gprpkdv9cve5yxqk4mkw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYkJWUGZHVDRZeHB2d2J2
            bks2Y1hPUTRsK1FXU1hCNllBMUZTRnh1T1Z3CmJiSk5JeW1DejR1THlvczZkaC9i
            TzRrVXl6OUxJNEtDaS9UR0pkUk1IeGsKLS0tIHJUeCsrMjlydGdraTVPVDJSbURG
            dW1mK3Jsd2JKTDd6SnBPd2MrQno3ZXMKThh/ciwCJyJUwhI+Qoi6uyaVI+u3herK
            +UqmJzX3kqSxNG82RMmJfqPmHkbAJlBJ4J1lKZ4PGN7GHlGVWhonjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12mql9lrqmp6yvrr9gh0kuuwnxn2hkvcku7x620vgtj6r568zfq7skkpajf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVHMxaDhGTXZBdGpZMjhC
            TnJGMUd4cUZhZVlxMHZpbVdJTnBtdkh1RmlVCkgwSWVReUFpcTFnbDB1bnI3dGht
            YzFid29hdDFpcUc3NzRCUHFCOEIyOTQKLS0tIHFENmtRak0yR1plYmZKUnpIeUJn
            VjRIc2FHWTNjQ0RkUU5zallubmpBSTAKiJ1JHlONoGqEUipLSp119H3dGuuvvu0G
            t1uXZrWHvI1rOTYGsv+ID+kZMXzkVLDkrECGy7hfZtUYCRhEtz8DhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13d0wge5xgtd8yvfak9lrhy5ee0yus7uecwhh0cpyqs59yv2ypveqt6evuh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R3hTS08zblVSMjcxYXYw
            T2x5TEhVa1VGUUIxUktXNER3OXJVZGNUUGtJCjRrUzM0QU5pbWZOVXJjc05YUjYw
            WXpsVWhnVDdZTlJRUUdvNEZNakZWd0EKLS0tIE9FNGR3RGc0NnRLUk41T081enpr
            Wk1Ga0xoaGRMc1Z4RmNGeFJOQTFDL0UKu+yUova+YSGo+4FrGBtaoRFwSh+wqjki
            4N3JBHtl+jdanyANAnvezzkjNn6UCy5YL2abOrvRySamhlsM8yaaNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T20:40:59Z"
    mac: ENC[AES256_GCM,data:JfIUE8lMiPQVS4Ixh34YwZ6sNqeeVTmmuj7plR1H8jF29t4GCvC8npuT9NE+YDMC3VQkR3eH54rtbPH+eLdfqARJXPZCULzQlT4ShffZHYvN6UqbWEV/wS6cD8mc6pPOGaaYMcfTbLXfQ8LUQpJcISqq6SAxUZkuPnOe349zq4g=,iv:l9J7t5d6+wrvLGgyuHysXkCsqdWaXr5zKAEuz39cr18=,tag:PsLQ4eWlHJC3j+MLHggUbQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
